tap 'alfr0475/formula'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'sanemat/font'
cask 'java'
brew 'android-sdk'
brew 'android-ndk'
brew 'awscli'
brew 'nkf'
brew 'cmigemo'
brew 'coreutils'
brew 'sqlite'
brew 'ffmpeg', args: ['with-libvorbis', 'with-libvpx']
brew 'figlet'
brew 'go'
brew 'ghq'
brew 'global'
brew 'gnutls'
brew 'htop-osx'
brew 'mysql'
brew 'peco'
brew 'putty'
brew 'reattach-to-user-namespace'
brew 'source-highlight'
brew 'tig'
brew 'tmux'
brew 'tmux-mem-cpu-load'
brew 'trash'
brew 'vim', args: ['with-lua']
brew 'wget'
brew 'alfr0475/formula/emacs-ime-patch', args: ['with-cocoa', 'with-gnutls']
brew 'homebrew/dupes/apple-gcc42'
brew 'sanemat/font/ricty', args: ['vim-powerline']
mas 'Xcode (8.0)', id: 497799835
mas '1Password (6.3.4)', id: 443987910
mas 'Caffeine (1.1.1)', id: 411246225
mas 'Wunderlist (3.4.5)', id: 410628904
mas 'LINE (4.9.0)', id: 539883307
mas 'MindNode (2.4.2)', id: 992076693
